version: '3'

services:
  #command: "simonpi rpi-3 -i /root/.simonpi/${SEED_IMAGE_FILENAME} -s 8"  #Example for a jinja replacement

  python:
    build: ./python/
    command: "python main.py"
    volumes:
      - $VOLUMES_FOLDER/python:/usr/src/app/
    networks:
      - my-app-network

networks:
  my-app-network:

